language: java
jdk:
  - openjdk8

services:
  - docker

before_install:
  - docker build -t h2-image .
  - docker run -d --name h2 -p 8080:8080 h2-image
  - docker ps -a
  

script:
  - java --version