apiVersion: v1
kind: PersistentVolume
metadata:
 name: h2-pv
 labels:
    failure-domain.beta.kubernetes.io/region: USSouth
    failure-domain.beta.kubernetes.io/zone: Dallas
spec:
 capacity:
   storage: 20Gi
 accessModes:
   - ReadWriteMany
 nfs:
   server: fsf-dal0902k-fz.service.softlayer.com
   path: /IBM02SEV2010994_2/data01
